### ISSUE TITLE
More obvious difference between retake and corrections

### ISSUE THREAD

**Issue by c-wegman** [UvA-FNWI/GradeTool#142]
### Component
Grade list submission

### Summary
More often corrections to final grades are submitted very late, in many cases only after the retake has taken place. This causes problems in the CRA/SIS because for a student who does not pass the exam a NAP is processed at the resit. If after that the exam is corrected to a pass, the credits are blocked by that NAP.

Also apart from these administrative issues, it is of course somewhat strange that months after a grade has been obtained something still needs to be repaired/corrected. The suspicion is that in many cases the student had not yet met all the requirements for the course and at a later time submits an additional assignment, etc. The idea then is that the new grade is entered as a retake: corrections are only for repair of errors.

#### New implementation
Make it more obvious that new grades only can be entered as a retake and that corrections are only for the repair of errors. By receiving pop ups when entering late corrections or a correction when the resit grade has already been entered.

### Reported by
FNWI (Reinout & Carla)

**Comment by jvdberge** [comment]
We had this suggestion on our list, which is so in line with this issue that I would like to add it here:
Please also make clear when correcting a first grade to a sufficient grade, where a student has already received an insufficient or lower resit grade, that this correction will not count, because of the registered resit grade with the later date. A solution might be to correct the resit grade or remove that.
