### ISSUE TITLE
Correction button is slow

### ISSUE THREAD

**Issue by goomens** [UvA-FNWI/GradeTool#59]
When adding a new correction it takes a while before the column appears and you get the idea that nothing happens. Add a loading screen (or speed it up sufficiently).

**Comment by rvankoten** [comment]
Added spinner when switcing to correction mode. Also it was mainly slow because it was syncing rights with SIS.
This resulted in hanging when running the tool locally. Performance wasn't very bad when on ACC.
Now skipping the sync when going to correction mode because rights don't change for corrections.
Also created new issue for improving overall performance of the gradetool
